<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AWT_Tester" failures="1" tests="6" name="com.awt.test.Login.VerifyLogInFunctionalityTest" time="365.356" errors="0" timestamp="2024-02-05T11:39:13 IST" skipped="2">
  <testcase classname="com.awt.test.Login.VerifyLogInFunctionalityTest" name="verifyLogInCredentialsTest" time="99.707">
    <failure message="The following asserts failed:
	expected [WELCOME TO NARMADA KSHIPRA MULTIPURPOSE PROJECT] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [WELCOME TO NARMADA KSHIPRA MULTIPURPOSE PROJECT] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.awt.utills.reusablecomponents.SoftAssertTest.assertAll(SoftAssertTest.java:154)
at com.awt.test.Login.VerifyLogInFunctionalityTest.verifyLogInCredentialsTest(VerifyLogInFunctionalityTest.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- verifyLogInCredentialsTest -->
  <system-out/>
  <testcase classname="com.awt.test.Login.VerifyLogInFunctionalityTest" name="verifyLogInCredentialsTest" time="99.303">
    <skipped/>
  </testcase> <!-- verifyLogInCredentialsTest -->
  <system-out/>
  <testcase classname="com.awt.test.Login.VerifyLogInFunctionalityTest" name="verifyLogInFunctionalityTest" time="41.455"/>
  <system-out/>
  <testcase classname="com.awt.test.Login.VerifyLogInFunctionalityTest" name="verifyLogInCredentialsTest" time="9.195"/>
  <system-out/>
  <testcase classname="com.awt.test.Login.VerifyLogInFunctionalityTest" name="verifyLogInCredentialsTest" time="105.040">
    <skipped/>
  </testcase> <!-- verifyLogInCredentialsTest -->
  <system-out/>
  <testcase classname="com.awt.test.Login.VerifyLogInFunctionalityTest" name="verifyLogInCredentialsTest" time="10.656"/>
  <system-out/>
</testsuite> <!-- com.awt.test.Login.VerifyLogInFunctionalityTest -->
